name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
        # this runs vcvarsall for us, so we get the MSVC toolchain in PATH.
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: build
        run: |
          cd Team34/Code34
          mkdir build
          cd build
          cmake -A Win32 .. &&
          cmake --build . --target unit_testing --config Release &&
          cmake --build . --target integration_testing --config Release && 
          cmake --build . --target autotester --config Release 
          if ($lastexitcode -ne 0) { throw "build failed" }
      - name: unit tests
        run: |
          cd Team34/Code34
          ./build/src/unit_testing/Release/unit_testing.exe
          if ($lastexitcode -ne 0) { throw "unit tests failed" }
      - name: integration tests
        run: |
          cd Team34/Code34
          ./build/src/integration_testing/Release/integration_testing.exe
          if ($lastexitcode -ne 0) { throw "integration tests failed" }
      - name: run autotester
        run: |
          cd Team34/Tests34
          python test_runner.py ..\Code34\build\src\autotester\Release\autotester.exe sys_tests_1 sys_tests_2 sys_tests_3
          if ($lastexitcode -ne 0) { throw "autotester failed" }
      - name: show failed tests
        run: |
          cd Team34/Tests34
          cat summary.txt
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: autotester-reports
          path: |
            Team34/Tests34/sys_tests_*/**.xml
            Team34/Tests34/summary.txt
  bench:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
        # this runs vcvarsall for us, so we get the MSVC toolchain in PATH.
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: build
        run: |
          cd Team34/Code34
          mkdir build
          cd build
          cmake -A Win32  .. -DENABLE_LOGGING=OFF -DENABLE_BENCHMARK=ON -DBENCHMARK_TO_STDERR=ON &&
          cmake --build . --target autotester --config Release  
          if ($lastexitcode -ne 0) { throw "build failed" }
      - name: run autotester
        run: |
          cd Team34/Tests34/bench
          ..\..\Code34\build\src\autotester\Release\autotester.exe bench.simple bench_queries.txt bench-out.xml > tmp.txt
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.12
      with:
        source: './Team34/Code34/src'
        clangFormatVersion: 12
