name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
        # this runs vcvarsall for us, so we get the MSVC toolchain in PATH.
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: install cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.21.x'
      - name: build
        run: |
          cd Team34/Code34
          mkdir build
          cd build
          cmake -A Win32 ..
          cmake --build . --target unit_testing --config Release
          cmake --build . --target integration_testing --config Release
          cmake --build . --target autotester --config Release
          if ($lastexitcode -ne 0) { throw "build failed" }
      - name: unit tests
        run: |
          cd Team34/Code34
          ./build/src/unit_testing/Release/unit_testing.exe
          if ($lastexitcode -ne 0) { throw "unit tests failed" }
      - name: integration tests
        run: |
          cd Team34/Code34
          ./build/src/integration_testing/Release/integration_testing.exe
          if ($lastexitcode -ne 0) { throw "integration tests failed" }
      - name: autotester
        run: |
          cd Team34
          Code34/build/src/autotester/Release/autotester.exe Tests34/Sample_source.txt Tests34/Sample_queries.txt out.xml
          if ($lastexitcode -ne 0) { throw "autotester failed" }
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.12
      with:
        source: './Team34/Code34/src'
